### ISSUE TITLE
License Incompatible with Clojure

### ISSUE THREAD

**Issue by mpemer** [JobtechSwe/jobtech-taxonomy-api#33]
Great work - however the GPLv3 license is not compatible with Clojure or Clojure libraries, which predominantly are licensed under EPL-1.0 or EPL-2.0. This code base, by being written in Clojure, thus breaks the GPL license itself. Please reconsider the choice of license used for all Clojure code - perhaps EPL-2.0 would be a more workable choice.

**Comment by weipe** [comment]
Thanks @mpemer for pointing this out! We will make a more workable choice!

**Comment by weipe** [comment]
Now we fixed the license issue. Thanks again for reporting!
